// Package direct implements the unencrypted PortTransit transport.
//
// It is the baseline: a TCP connection followed by a preamble. It is fast and
// has no handshake overhead, and it is appropriate when the hop between client
// and relay is already protected — for example a relay reached over a private
// network, an SSH port-forward, or a WireGuard tunnel.
//
// # When not to use it
//
// On the public internet the preamble and the relayed payload are both in
// cleartext, so anyone on the path can read the destination and the traffic.
// The Web GUI marks this transport as unsafe and requires an explicit
// confirmation before it is added to a public server.
//
// # Wire format
//
//	client → relay: [PortTransit preamble]
//	relay  → client: (nothing; the relay dials the target)
//	then:           raw bidirectional bytes
package direct

import (
	"context"
	"net"
	"time"

	"porttransit/internal/logx"
	"porttransit/internal/transport"
)

// Name is the registry key.
const Name = "direct"

// DefaultPort is the conventional listen port. It matches the port commonly
// used for plain TCP relays so firewall rules stay predictable.
const DefaultPort = 8080

func init() {
	transport.Register(transport.Factory{
		Name:         Name,
		Description:  "Plain TCP with an authenticated preamble. No encryption — use only over an already-protected link.",
		NativeHeader: false,
		DefaultPort:  DefaultPort,
		Build:        func() (transport.Dialer, transport.Handler) { return Dialer{}, Handler{} },
	})
}

// Settings keys understood by this transport.
const (
	// SettingPSK is the base64 or raw pre-shared key used to authenticate the
	// preamble. An empty value disables MAC verification, which is only safe
	// on a fully trusted link.
	SettingPSK = "psk"
	// SettingTimeout bounds the handshake.
	SettingTimeout = "timeout"
)

// Dialer establishes client→relay direct streams.
type Dialer struct{}

// Name returns the registry key.
func (Dialer) Name() string { return Name }

// Dial opens a TCP connection and exchanges the preamble.
func (d Dialer) Dial(ctx context.Context, req transport.DialRequest) (transport.Stream, error) {
	timeout := req.Settings.GetDuration(SettingTimeout, 10*time.Second)
	if req.Timeout > 0 {
		timeout = req.Timeout
	}

	conn, err := dialTCP(ctx, req.ServerAddr, timeout)
	if err != nil {
		return nil, err
	}

	return transport.PreambleClientHandshake(conn, req.Request, transport.ClientHandshakeConfig{
		PSK:           pskFrom(req.Settings),
		ClientID:      clientIDFrom(req.Settings, req.Request),
		TransportName: Name,
		Timeout:       timeout,
		Logger:        loggerFor(req.Logger),
	})
}

// Handler accepts relay-side direct streams.
type Handler struct{}

// Name returns the registry key.
func (Handler) Name() string { return Name }

// Handle reads the preamble from an accepted connection.
func (h Handler) Handle(ctx context.Context, raw net.Conn, req transport.HandleRequest) (transport.Stream, error) {
	timeout := req.Settings.GetDuration(SettingTimeout, 10*time.Second)
	if req.Timeout > 0 {
		timeout = req.Timeout
	}

	return transport.PreambleServerHandshake(raw, transport.ServerHandshakeConfig{
		PSK:             pskFrom(req.Settings),
		Replay:          replayFrom(req.Settings),
		Timeout:         timeout,
		Logger:          loggerFor(req.Logger),
		RequireClientID: req.Settings.GetBool("requireClientID", false),
		AllowedClients:  req.Settings.GetStringSlice("allowedClients"),
		AllowPing:       req.Settings.GetBool("allowPing", true),
		TransportName:   Name,
	})
}

// pskFrom reads the pre-shared key. Both a raw string and a base64 string are
// accepted so a key generated by the GUI round-trips unchanged.
func pskFrom(s transport.Settings) []byte {
	return transport.DecodePSK(s.GetString(SettingPSK, ""))
}

func replayFrom(s transport.Settings) *transport.ReplayGuard {
	if s.GetBool("disableReplayGuard", false) {
		return nil
	}
	cap := s.GetInt("replayCacheSize", 65536)
	return transport.NewReplayGuard(cap, 0)
}

func clientIDFrom(s transport.Settings, req *transport.Request) string {
	if req != nil && req.ClientID != "" {
		return req.ClientID
	}
	return s.GetString("clientID", "")
}

func dialTCP(ctx context.Context, addr string, timeout time.Duration) (net.Conn, error) {
	nd := net.Dialer{Timeout: timeout, KeepAlive: 30 * time.Second}
	return nd.DialContext(ctx, "tcp", addr)
}

// loggerFor adapts the shared logger to the transport package's minimal
// interface.
//
// It returns an explicit no-op rather than nil: a nil interface panics on the
// first method call, and the transports log from inside handshake paths where
// a panic would take down the whole relay.
func loggerFor(l *logx.Logger) transport.Logger {
	if l == nil {
		return transport.NopLogger()
	}
	return l
}
